-- This query generates the commons_pageviews_per_media_file_monthly dataset
-- described in https://docs.google.com/document/d/1AyorlFViHL2hj_6Sss4NRmKeqkk6XiV-EFb8uqyhla0
-- It needs the data generated by category_and_media_with_usage_map.hql
--
-- Parameters:
--     category_and_media_with_usage_map_table         -- Read data from here
--     commons_pageviews_per_media_file_monthly_table  -- Insert results here
--     year_month                                      -- YYYY-MM to compute for
--     coalesce_partitions                             -- Number of partitions to write
--
-- Usage:
--     spark3-sql -f commons_pageviews_per_media_file_monthly.hql \
--                -d category_and_media_with_usage_map_table=tmp.category_and_media_with_usage_map \
--                -d commons_pageviews_per_media_file_monthly_table=wmf_contributors.commons_pageviews_per_media_file_monthly \
--                -d year_month=2024-02 \
--                -d coalesce_partitions=4

DELETE
FROM ${commons_pageviews_per_media_file_monthly_table}
WHERE year_month = '${year_month}';

WITH glam_media_files_with_categories AS (
         SELECT page_title AS media_file,
                map_values(primary_categories) AS primary_categories,
                map_values(parent_categories) AS categories,
                usage_map
         FROM ${category_and_media_with_usage_map_table}
         WHERE page_type = 'file'
     ),

     glam_media_files_exploded_by_wiki_db AS (
         SELECT media_file,
                primary_categories,
                categories,
                EXPLODE(usage_map) AS (wiki, pages)
         FROM glam_media_files_with_categories),

     glam_media_files_exploded_by_article AS (
         SELECT media_file,
                primary_categories,
                categories,
                wiki,
                EXPLODE(pages) AS (page_title, pageview_count)
         FROM glam_media_files_exploded_by_wiki_db),

     full_glam_media_files AS (
         SELECT media_file,
                categories,
                primary_categories,
                wiki,
                page_title,
                pageview_count,
                '${year_month}' AS year_month
         FROM glam_media_files_exploded_by_article)

INSERT
INTO ${commons_pageviews_per_media_file_monthly_table}
SELECT /*+ COALESCE(${coalesce_partitions}) */
       *
FROM full_glam_media_files
;
